madrid/common/urls.py
from django.urls import path
from . import views
 
app_name='common'   #for redirection purpose

urlpatterns=[
    path('',views.home,name='home'),
    path('fixtures',views.fixtures,name='fixtures'),
    path('madridistas',views.madridistas,name='madriditas'),
    path('players',views.players,name='players'),
    path('stores',views.stores,name='stores')
]

madrid/madrid/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls'))

]

madrid/common/models.py
from django.db import models

# Create your models here.

madrid/common/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request,'common/home.html')

def fixtures(request):
    return render(request,'common/fixtures.html')

def madridistas(request):
    return render(request,'common/madridistas.html')

def players(request):
    return render(request,'common/players.html')

def stores(request):
    return render(request,'common/stores.html')            

madrid/common/templates/common/fixtures.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    fix
</body>
</html>

madrid/common/templates/common/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">
    <title>Document</title>
    <style>
        * {
            font-family: 'Rubik', sans-serif;
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        /* body {
            position: relative;
        } */

        header {
            height: 100px;
            display: flex;
            justify-content: space-between;
            padding: 0px 60px;
            align-items: center;
            border-bottom: 1px solid black;
            position: fixed;
            top: 0;
            z-index: 1;
            width: 100%;
            background-color: #ffff;
        }

        .logo img {
            height: auto;
            width: 70px;
        }

        header .links {
            display: flex;
            gap: 10px;
        }

        header a {
            color: black;
            text-decoration: none;
        }


        .body {
            display: grid;
            grid-template-columns: 238px auto auto;
            grid-template-rows: 50% 50%;
            margin-top: 100px;
        }

        .div1 {
            grid-area: 1/1/3/2;
        }

        .div2 {
            grid-area: 1/2/2/4;
        }

        .div2 img {
            height: fit-content;
            width: 100%;
            height: 100%;
        }

        /* .div3 {
            grid-area: 1/3/2/4;
        } */

        .div3 img {
            width: 100%;
            height: 100%
        }

        .div4 {
            grid-area: 2/2/3/3;
        }

        .div5 {
            grid-area: 2/3/3/4;
        }

        div>img {
            width: 100%;
            height: 100%
        }

        
        .footer {
            display: grid;
            grid-template-columns: 20% 30% 50%;
            grid-template-rows: 100px;
            justify-content: center;
            align-content: center;
            border: 2px solid wheat;
        }

        .f1 img {
            height: 100%;
            width: 100%;
            padding-left: 14px;
        }

        .f2 h2 {
            color: rgb(196, 119, 26);

        }

        .f2 img {
            height: 40px;
            width: 40px;


        }

        .f2 table {
            padding-top: 16px;
            padding-left: 128px;
        }

        .f3 img {
            height: 50px;
            width: 50px;
        }

        .f3 table {
            
            padding-left: 400px;
        }
        .div4 h1{
            padding-top: 150px;
            padding-left: 50px;
            font-style: italic;
            
        }
        .div4 h1:hover{
            color: rgb(225, 109, 14);
        }
    </style>
</head>

<body>
    <header>
        <div class="logo">
            <img src="{% static 'C:\Users\lenovo t 480s\Desktop\madrid\madrid\common\static\images\logo3.png' %}"
                alt="">
        </div>
        <div class="links">
            <a href="{% url 'common:stores' %}">store</a>
            <a href="{% url 'common:players' %}">players</a>
            <a href="#">madridistas</a>
            <a href="#">fixtures</a>
        </div>

    </header>

    <div class="body">
        <div class="div1" style="border: 2px solid wheat; border-right: none;"><img src="{% static 'images/ben.png' %}"
                alt=""></div>
        <div class="div2" style="border: 2px solid wheat;"><img src="{% static 'images/cortua.jpg' %}" alt=""></div>
        <!-- <div class="div3"><img src="{% static 'images/skin.jpg' %}" alt=""></div> -->
        <div class="div4">
            <h1>next match ></h1>
        </div>
        <div class="div5"><img src="{% static 'images/barca.webp' %}" alt=""></div>



    </div>
    
       
        <div class="footer"> 
        <div class="f1"><img src="{% static 'images/footerlogo.svg' %}" alt=""></div>
        <div class="f2">
            <table>
                <tr>
                    <th>follow us on</th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/insta.png' %}" alt="">
                        <img src="{% static 'images/fb.png' %}" alt="">
                        <img src="{% static 'images/twit.png' %}" alt="">
                        </dh>
                </tr>
            </table>
        </div>
        <div class="f3">
            <table cellspacing="10px" cellpadding="50px">
                <tr>
                    <th colspan="2">
                        <h3><u>sponsors</u></h3>
                    </th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/adidas.png' %}" alt="">
                    </td>
                    <td> <img src="{% static 'images/emirates.png' %}" alt="">
                    </td>
                    
                </tr>

            </table>
        </div>
    </div>
</body>

</html>

madrid/common/templates/common/madridistas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="1">
      <h2>
        with your madridista prime card you will have the priority in the purchase of tickets and access to presales,exclusive guided tours and 20% discount 
      </h2>
    </div>
</body>
</html>

madrid/common/templates/common/players.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">
    <title>Document</title>
    <style>
        * {
            font-family: 'Rubik', sans-serif;
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        /* body {
            position: relative;
        } */

        header {
            height: 100px;
            display: flex;
            justify-content: space-between;
            padding: 0px 60px;
            align-items: center;
            border-bottom: 1px solid black;
            position: fixed;
            top: 0;
            z-index: 1;
            width: 100%;
            background-color: #ffff;
        }

        .logo img {
            height: auto;
            width: 70px;
        }

        header .links {
            display: flex;
            gap: 10px;
        }

        header a {
            color: black;
            text-decoration: none;
        }

        .body {
            display: grid;
            grid-template-columns: 50% 50%;
            grid-template-rows: 100px auto;
            margin-top: 100px;
        }

        .available {
            grid-area: 1/1/2/3;
            border: 2px solid wheat;
        }

        .available img {
            height: 100%;
            width: 100%;
        }

        .side {
            grid-area: 2/1/3/2;
        }

        .main {
            grid-area: 2/2/3/3;
        }

        .main .players {
            display: flex;
            height: 100%;
        }

        .players .benzema {
            flex-grow: 8;
        }

        .players .vinic {
            flex-grow: 8;
        }

        .players .next {
            flex: 2;
            align-self: center;
            padding-right: 20px;
        }
        .players .next a{
            text-decoration: none;
        }

        .players div img {
            height: 100%;
            width: 100%;
        }
        
            .footer {
            display: grid;
            grid-template-columns: 20% 30% 50%;
            grid-template-rows: 100px;
            justify-content: center;
            align-content: center;
            border: 2px solid wheat;
        }

        .f1 img {
            height: 100%;
            width: 100%;
            padding-left: 14px;
        }

        .f2 h2 {
            color: rgb(196, 119, 26);

        }

        .f2 img {
            height: 40px;
            width: 40px;


        }

        .f2 table {
            padding-top: 16px;
            padding-left: 128px;
        }

        .f3 img {
            height: 50px;
            width: 50px;
        }

        .f3 table {
            
            padding-left: 400px;
        }
    </style>
</head>

<body>
    <header>
        <div class="logo">
            <img src="{% static 'C:\Users\lenovo t 480s\Desktop\madrid\madrid\common\static\images\logo3.png' %}"
                alt="">
        </div>
        <div class="links">
            <a href="{% url 'common:home' %}">home</a>
            <a href="{% url 'common:stores' %}">store</a>
            
            <a href="#">madridistas</a>
            <a href="#">fixtures</a>
        </div>

    </header>
    <div class="body">
        <div class="available"><img src="{% static 'images/ava.gif' %}" alt=""></div>
        <div class="side"><img src="{% static 'images/ase.png' %}" alt=""></div>
        <div class="main">
            <div class="players">
                <div class="benzema"><img src="{% static 'images/ikka.png' %}" alt=""></div>
                <div class="vinic"><img src="{% static 'images/vinic.png' %}" alt=""></div>
                <div class="next"><a href=""><h1>next</h1></a></div>
            </div>
        </div>
    </div>
    
    <div class="footer"> 
        <div class="f1"><img src="{% static 'images/footerlogo.svg' %}" alt=""></div>
        <div class="f2">
            <table>
                <tr>
                    <th>follow us on</th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/insta.png' %}" alt="">
                        <img src="{% static 'images/fb.png' %}" alt="">
                        <img src="{% static 'images/twit.png' %}" alt="">
                        </dh>
                </tr>
            </table>
        </div>
        <div class="f3">
            <table cellspacing="10px" cellpadding="50px">
                <tr>
                    <th colspan="2">
                        <h3><u>sponsors</u></h3>
                    </th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/adidas.png' %}" alt="">
                    </td>
                    <td> <img src="{% static 'images/emirates.png' %}" alt="">
                    </td>
                    
                </tr>

            </table>
        </div>
    </div>
</body>

</html>

madrid/common/templates/common/stores.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300&display=swap" rel="stylesheet">
    <title>Document</title>
    <style>
        * {
            font-family: 'Rubik', sans-serif;
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }

        header {
            height: 100px;
            display: flex;
            justify-content: space-between;
            padding: 0px 60px;
            align-items: center;
            border-bottom: 1px solid black;
            position: fixed;
            top: 0;
            z-index: 1;
            width: 100%;
            background-color: #ffff;
        }

        .logo img {
            height: auto;
            width: 70px;
        }

        header .links {
            display: flex;
            gap: 15px;
        }

        header a {
            color: black;
            text-decoration: none;
        }

        .body {
            display: grid;
            position: relative;
            margin-top: 100px;
            grid-template-columns: 30% 70%;
            grid-template-rows: auto auto;
            height: 100%;
        }

        .search {
            grid-area: 1/1/2/3;
            width: 100%;
            align-self: center;
            /* height: 60px; */
        }

        .search img {
            padding-left: 20px;
        }

        .aside {
            grid-area: 2/1/3/2;
            border: 2px solid wheat;

        }

        .middle {
            grid-area: 2/2/3/3;
        }

        .search {
            display: flex;
            column-gap: 10px;
            /* flex-wrap: wrap; 
        flex-flow: row wrap; */
            justify-content: space-between;
            align-content: center;

        }

        .search_area {
            display: flex;
            align-items: center;
            margin-right: 50px;

        }

        .search_area input {
            height: 30px;
        }

        .icon {
            display: flex;
            align-items: center;
            /* flex-grow: 3; */
        }

        .icon img {
            height: 70px;
        }
        
            .footer {
            display: grid;
            grid-template-columns: 20% 30% 50%;
            grid-template-rows: 100px;
            justify-content: center;
            align-content: center;
            border: 2px solid wheat;
        }

        .f1 img {
            height: 100%;
            width: 100%;
            padding-left: 14px;
        }

        .f2 h2 {
            color: rgb(196, 119, 26);

        }

        .f2 img {
            height: 40px;
            width: 40px;


        }

        .f2 table {
            padding-top: 16px;
            padding-left: 128px;
        }

        .f3 img {
            height: 50px;
            width: 50px;
        }

        .f3 table {
            
            padding-left: 400px;
        }
    </style>
</head>

<body>
    <header>
        <div class="logo">
            <img src="{% static 'C:\Users\lenovo t 480s\Desktop\madrid\madrid\common\static\images\logo3.png' %}"
                alt="">
        </div>
        <div class="links">
            <a href="{% url 'common:home' %}">home</a>
            <a href="{% url 'common:players' %}">players</a>
            <a href="#">madridistas</a>
            <a href="#">fixtures</a>
        </div>

    </header>
    <div class="body">
        <div class="search">

            <div class="image"><img src="{% static 'images/store.avif' %}" alt=""></div>
            <div class="search_area">
                <input type="text" size="60" placeholder="search" height="50px">
                <div class="icon">
                    <img src="{% static 'images/soccer.png' %}" alt="">
                </div>
            </div>


        </div>
        <div class="aside"><img src="{% static 'images/keep.webp' %}" alt="" style="width: 100%; height: 100%;"></div>
        <div class="middle"><img src="{% static 'images/mili.webp' %}" alt="" style="width: 100%; height: 100%;"></div>
    </div>
    
    <div class="footer"> 
        <div class="f1"><img src="{% static 'images/footerlogo.svg' %}" alt=""></div>
        <div class="f2">
            <table>
                <tr>
                    <th>follow us on</th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/insta.png' %}" alt="">
                        <img src="{% static 'images/fb.png' %}" alt="">
                        <img src="{% static 'images/twit.png' %}" alt="">
                        </dh>
                </tr>
            </table>
        </div>
        <div class="f3">
            <table cellspacing="10px" cellpadding="50px">
                <tr>
                    <th colspan="2">
                        <h3><u>sponsors</u></h3>
                    </th>
                </tr>
                <tr>
                    <td>
                        <img src="{% static 'images/adidas.png' %}" alt="">
                    </td>
                    <td> <img src="{% static 'images/emirates.png' %}" alt="">
                    </td>
                    
                </tr>

            </table>
        </div>
    </div>
</body>

</html>